In [32]:
import pandas as pd

df = pd.read_json('../data/MATH_100/MATH_100.jsonl', lines=True, orient='records')

df.head()

,problem,solution,full_cot,steps,total_steps,first_essp_index,step_accuracies,essp_indices,answer
0,The coordinates of the vertices of isosceles t...,"For simplicity, we translate the points so tha...","<think>\nOkay, so I need to solve this problem...","[Okay, so I need to solve this problem about a...",1221,1211,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1211, 1211, 1212, 1213, 1214, 1215, 1216, 121...",131
1,"A fenced, rectangular field measures $24$ mete...",Suppose there are $n$ squares in every column ...,"<think>\nOkay, so I need to figure out how to ...","[Okay, so I need to figure out how to partitio...",464,217,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[217, 217, 218, 219, 220, 221, 222, 223, 224, ...",702
2,The sides of a triangle with positive area hav...,"By the Triangle Inequality, each of $x$ and $y...","<think>\nOkay, so I need to figure out the sma...","[Okay, so I need to figure out the smallest po...",251,13,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[13, 13, 14, 15, 16, 17, 22, 24, 25, 26, 27, 2...",8
3,If $n$ is a positive integer such that $2n$ ha...,"Let $\, 2^{e_1} 3^{e_2} 5^{e_3} \cdots \,$ be ...","<think>\nOkay, so I need to figure out how man...","[Okay, so I need to figure out how many positi...",189,14,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[14, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 2...",35
4,The Annual Interplanetary Mathematics Examinat...,Since the 5 members of each planet committee a...,"<think>\nOkay, so I need to figure out the num...","[Okay, so I need to figure out the number of p...",656,573,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[573, 573, 574, 575, 576, 577, 578, 579, 580, ...",346

In [33]:
df = df.sort_values(by=['total_steps'], ascending=True)[8:]

df.to_json('../data/MATH_100/MATH_92.jsonl', lines=True, orient='records')

In [37]:
df

,problem,solution,full_cot,steps,total_steps,first_essp_index,step_accuracies,essp_indices,answer
18,Suppose that $x_1+1=x_2+2=x_3+3=\cdots=x_{2008...,"Note that for a given integer $a$, where $1 \l...","<think>\nOkay, so I need to solve this problem...","[Okay, so I need to solve this problem where t...",134,79,"[0.0, 0.0, 0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[79, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 8...",1005
56,If\n\[(1 + \tan 1^\circ)(1 + \tan 2^\circ)(1 +...,"Note that for any angle $x,$ from the angle su...","<think>\nOkay, so I need to find the value of ...","[Okay, so I need to find the value of $ n $ su...",152,11,"[0.2, 0.25, 0.15, 0.15, 0.30000000000000004, 0...","[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 2...",23
96,"As shown, a square is constructed on the hypot...","$\triangle CDE$ is a 3-4-5 right triangle, so ...","<think>\nOkay, so I need to find the area of t...","[Okay, so I need to find the area of this pent...",176,93,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[93, 93, 109, 110, 111, 112, 113, 114, 115, 11...",31
72,If you continue this pattern in which each lin...,"In the transition between figures, each endpoi...","<think>\nOkay, so I need to figure out how man...","[Okay, so I need to figure out how many endpoi...",181,72,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[72, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 8...",48
22,Define $f(x)=\frac{1+x}{1-x}$ and $g(x)=\frac{...,Define a new function $h(x)$ so that $h(x)=g(f...,"<think>\nOkay, so I need to figure out this pr...","[Okay, so I need to figure out this problem wh...",181,45,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[45, 45, 47, 54, 55, 56, 57, 58, 59, 60, 61, 6...",4
...,...,...,...,...,...,...,...,...,...
64,The sum of the areas of all triangles whose ve...,[asy] size(120); defaultpen(linewidth(0.5)); i...,"<think>\nOkay, so I need to find the sum of th...","[Okay, so I need to find the sum of the areas ...",1154,980,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[980, 980, 981, 982, 983, 984, 985, 986, 987, ...",348
42,Find the sum of all positive integers $n$ such...,"By the Chicken McNugget theorem, the least pos...","<think>\nOkay, so I need to find all positive ...","[Okay, so I need to find all positive integers...",1205,596,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[596, 596, 901, 902, 903, 904, 905, 906, 907, ...",71
0,The coordinates of the vertices of isosceles t...,"For simplicity, we translate the points so tha...","<think>\nOkay, so I need to solve this problem...","[Okay, so I need to solve this problem about a...",1221,1211,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1211, 1211, 1212, 1213, 1214, 1215, 1216, 121...",131
83,"A set $S$ is constructed as follows. To begin,...","We start with the set $S = \{0,10\}.$ We can ...","<think>\nOkay, so I need to figure out how man...","[Okay, so I need to figure out how many elemen...",1523,709,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[709, 709, 710, 729, 1303, 1308, 1310, 1321, 1...",9
98,Let $m$ and $n$ be positive integers satisfyin...,Taking inspiration from $4^4 \mid 10^{10}$ we ...,"<think>\nOkay, so I need to find the smallest ...","[Okay, so I need to find the smallest possible...",2135,9,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[9, 9, 762, 763, 776, 801, 834, 1047, 1048, 10...",407